### PR TITLE
Memory control via PINE

### PR DESCRIPTION
**Pull request by TheUbMunster**
Hello!

This is my attempt at implementing PINE memory control. There are a few issues, mostly related to performance. I have several ideas written down in comments, and a few more that I'll likely try tomorrow.

Something that would assist my diagnosis, is that it _seems_ that if [this](https://github.com/CTR-tools/CTR-ModSDK/blob/1fb2d1058593af31e58ee8d23269d9b5819de4c4/mods/Windows/OnlineCTR/Network_PC/Client/CL_main.c#L1134) while loop at the bottom of CL_main.c runs sufficiently slow, then CTR in duckstation is never able to achieve reaching the server selection screen. I'm pretty sure this is the case because if I put a breakpoint in that loop and manually spam the continue button in the debugger, it never gets to the server selection screen, but the second I remove it, it suddenly works again.

The reason this is an issue in my code is because much of the memory management that takes place during that loop is slow enough to replicate this issue, even though I **think** the code is behaving logically correct.

If someone can inform me about why this behavior occurs, that would be great.

Additionally, here's some profiling information I took of the current version, and my pine version:

## PINE as of d8174218
pine

## MAIN as of 27c7750c
main

Github won't let me upload them here, but contact me if you wish to look at both .diagsession files.

Additionally, even though "main" has a very red FrameStall line, keep in mind that the percentages of where the CPU spends it's time is relative. If 70% of the CPU's time is spent on FrameStall(), that just means all the other work gets completed super quick.

As you can see, PINE spends almost 50% of it's time in that while loop, so optimizing it is important. I'm going to be doing some optimizations to reduce PINE requests. buffering the sockets, and some other stuff which will probably help a lot.

Also, I changed the CL_main.c into cpp because my initial attempts (see my early commits on the pine branch) resulted in hypothetically function but extremely ugly code that's easy to implement incorrectly, and the new sugar that cpp brings allows for very concise memory management (E.g., everything to do with `octr`, and somewhat `Gamepad`)

If at some point, instead of manipulating with raw memory addresses, we properly create type definitions for all CTR's data, propagate those types throughout memory, essentially all of our memory accesses will be clean looking.

If you have any questions about design decisions, I'm willing to talk about and reconsider them.

### CODE REVIEW

**Comment by TheUbMunster** [comment]
After some optimization, here's PINE as of 8b767009
image
(this includes the changes from PR #145)

At this point, OnlineCTR acknowledges CLIENT.EXE and goes to the server select screen, but very shortly afterwards (1-2 seconds), it gets "stuck" in FrameStall() and never really leaves.

I'm making a lot of assumptions here, but maybe:
- The purpose of FrameStall() is to prevent CLIENT.EXE from "getting too far ahead" of the game.
- Somehow the (almost certainly larger) latency involved with fetching memory is causing CLIENT.EXE to "get too far ***behind***" the game.
- If lockstep was the goal, hypothetically one should "stall" the game (which we can't do), but instead the game continues to get further and further ahead
- ?This confuses CLIENT.EXE and for some reason it gets stuck in FrameStall()?

I'm not sure what leap in implementation would require getting from that second-to-last-step to the last step, but that seems to be the case. I'm working on further reducing round-trip latency from PINE, but maybe (a bit too soon to say), it won't be possible to sufficiently reduce the latency from PINE to permit real-time memory communication from the game, and that some things will have to be re-made to allow asynchronous communication between the game and the networking client.

Will be further optimizing, hope this won't be necessary.

**Comment by TheUbMunster** [comment]
It seems I've made a mistake when it comes to interpreting the meaning of some of the crazy dereferencing

like this: `*(int*)&pBuf[(0x80096b20 + 0x1cf8) & 0xffffff]`

I thought this was double indirection, but it was not. I likely have to correct certain sections of code and it probably will work.

**Comment by bemug** [comment]
I see you're working a lot on this. Thanks a lot.

Just a quick head-up, I see you're using winsock2. It was replaced by enet in later builds.
I have as goal to build your PR on Linux, hence supporting enet is important as it is portable. Winsock2 is limited to Windows.

**Comment by TheUbMunster** [comment]
> I see you're working a lot on this. Thanks a lot.
> 
> Just a quick head-up, I see you're using winsock2. It was replaced by enet in later builds. I have as goal to build your PR on Linux, hence supporting enet is important as it is portable. Winsock2 is limited to Windows.

Unfortunately, it seems [enet is intended for UDP](http://enet.bespin.org/) (it may do more than that, I'm just reading the first page), and PINE uses TCP.

Given that the (networking) client and server for CTROnline are both being developed/controlled by the same developers, it's easy to take whatever library works best for them and run with it, however, when it comes to PINE support for Duckstation, I don't have the luxury of choosing how & what the PINE API is written with and with what high-level protocol.

If enet does indeed support TCP, and it is possible to use it without any protocol whatsoever (so that the PINE protocol can be implemented on top of it), I don't really have much of a problem with switching to enet before unmarking this as a draft.

Many networking libraries implement notions of things like "channels" and other sugar to make powerful communication systems easily, but that would get in the way in this case, and just by looking at the existing enet code, it seems like I'd be signing up for a bunch of features that at best will never get used, and at worst will just get in the way. It might just end up being treated as a glorified "cross platform socket wrapper library" for the sake of PINE.

DeferredMem.cpp/h was separated from CL_main to make it easier to implement different networking backends via the preprocessor, which I don't think will be that hard.

At this point, PINE support is kind of working, and now it's just down to ironing out bugs.

If I've made any false assumptions when it comes to enet, or am missing critical information, let me know. Regardless, I will spend some time this week into reading up on enet to see if I can get that to work.

**Comment by bemug** [comment]
I was not aware that enet is UDP only. Apparently it is some kind of layer over UDP.
Then I'll need to implement a new socket backend in DeferredMem.cpp with POSIX sockets I guess.

**Comment by TheUbMunster** [comment]
I think this PR has met a good standard of quality, however, there are some issues that might need to be resolved:

- Unlike before (where the duckstation process was grabbed and the memory was mapped into this process), it's just tcp communication over localhost on port 28011. Currently, duckstation needs to be started *first*, and then the client.exe needs to be started. If duckstation is closed, the client.exe exits. Even if the client just re-called main in this circumstance, since duckstation was just closed, the application would re-open to find that duckstation isn't running, and then close itself.
- The TCP communication, though streamlined, still introduces enough latency w/blocking reads (but non-blocking writes, thankfully), that the amount of updates that the game can send to the game server per second is probably lower than the current version. It's unknown how this scales with >2 players, as I only have two computers to test with.

There is almost certainly more optimization that can be had, however, most of the ones I've thought of require underlying assumptions that I don't have enough knowledge of. Specifically, I want to know what race conditions existed between the client.exe and ps1 game before, and how they were handled. If there's little to no synchronization because the game has worked fine without it, then it's likely the case that many more "unsafe" optimizations can be made.

I'm unmarking this PR as a draft because I want people to test it and give feedback.

Note that this version is not compatible with current xdeltas and servers. You will have to compile the client.exe, server.exe, and .xdelta/bin&cue yourself for testing.

**Comment by TheUbMunster** [comment]
> * Currently, duckstation needs to be started _first_, and then the client.exe needs to be started. If duckstation is closed, the client.exe exits. Even if the client just re-called main in this circumstance, since duckstation was just closed, the application would re-open to find that duckstation isn't running, and then close itself.

This has been changed so that the program execv's itself if it ever "fails", including if when after the user types in their username, duckstation isn't running.

At this point we just need testing to verify no crazy bugs.

**Comment by TheUbMunster** [comment]
Redhot and I had a long conversation about this, and we think that it's a much better idea at this point to pursue duckstation's python API. Even with all the optimizations that have been made, the best that can be said about this PINE implementation is that "it's sufficient for time trial, but not usable for weapons."

**Pull request merged**
