### PR TITLE
Add online client support for linux

### PR DESCRIPTION
**Pull request by bemug**
This won't work as is and requires a patch in duckstation to expose shared memory in Linux.
Later we will refactor the client to use PINE to access memory, instead of shmem.

### CODE REVIEW

**Comment by bemug** [comment]
I don't have access to a Windows platform. Could anyone try it before merging ?

**Review by PedroHLC — APPROVED** [review]
LGTM

**Comment by GreyXor** [comment]
@bemug hello, can you rebase with latest fixes ? https://github.com/CTR-tools/CTR-ModSDK/commits/main/mods/Windows/OnlineCTR/Network_PC/Client/CL_main.c
Thanks :)

**Comment by bemug** [comment]
I'm sorry but I won't.

As the duckstation fork will not get merged, I'd rather focus on implementing PINE support instead.
This will enable Linux the proper way, and secure the Windows build too as the shared memory support will be dropped.
I'm not sure when I'll have a time slot to do so, feel free to give it a go :)

**Comment by GreyXor** [comment]
> I'm sorry but I won't.
> 
> As the duckstation fork will not get merged, I'd rather focus on implementing PINE support instead. This will enable Linux the proper way, and secure the Windows build too as the shared memory support will be dropped. I'm not sure when I'll have a time slot to do so, feel free to give it a go :)

Alright, I didn't knew we'll take this path. I have no idea about PINE, I will check with no promises

**Comment by GreyXor** [comment]
I'm stuck with the pine memory address mapping.
```C
octr = (struct OnlineCTR*)&pBuf[0x8000C000 & 0xffffff];
```
Here is the current OnlineCTR mapping, i'm just not sure where the game memory from pine is beginning. Would it be `0000C0000` then ?

**Comment by bemug** [comment]
I'm afraid I can't help you, I didn't tinkered with the memory mapping yet. Niko should know more about this.
Keep us posted. Good luck !

**Pull request closed without merging**
